name: Convert YAML to JSON

on:
  push:
    paths:
      - 'src/_data/*.yml'
      - '.github/workflows/yaml-to-json.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: âœ… Checkout repository
        uses: actions/checkout@v3

      - name: ðŸ”§ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: ðŸ“¦ Install dependencies
        run: npm install
        #working-directory: src/_data

      - name: ðŸ” Convert YAML to JSON
        run: npm run convert
        #working-directory: src/_data

      - name: ðŸš€ Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
      - name: Add JSON files if they exist
        run: |
          if ls src/data/*.json 1> /dev/null 2>&1; then
            git add src/data/*.json
          else
            echo "No JSON files to add."
          fi          
          git add src/data/*.json
          git commit -m "ðŸ”„ Auto-convert YAML to JSON" || echo "No changes to commit"
          git push origin main
